apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
  namespace: thetrains
  labels:
    app: mongo
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 20Gi
  storageClassName: microk8s-hostpath