apiVersion: apps/v1
kind: Deployment
metadata:
  name: thetrains
  namespace: thetrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thetrains
  template:
    metadata:
      labels:
        app: thetrains
    spec:
      containers:
      - name: thetrains
        image: registry.gitlab.com/joshtingey/thetrains/thetrains:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000