# .gitlab-ci.yml
image: "docker:latest"
services:
  - docker:dind   

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

test_python:
  stage: test
  script:
    - python --version
  
test_environment:
  stage: test
  script:
    - source ./scripts/environment_test.sh

test_docker_compose:
  stage: test
  script:
    - docker-compose --version