# .gitlab-ci.yml
image: "tiangolo/docker-with-compose"
services:
  - docker:dind   

test_python:
  stage: test
  script:
    - python --version
  
test_environment:
  stage: test
  script:
    - source ./scripts/environment_test.sh

test_docker_compose:
  stage: test
  script:
    - docker-compose --version

test_collector:
  stage: test
  script:
    - python collector/collector.py