# .gitlab-ci.yml
image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test  

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-dash:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE dash/
    - docker push $TEST_IMAGE
  
test_env:
  stage: test
  script:
    - source ./scripts/environment_test.sh