# .gitlab-ci.yml

stages:
  - test
  - release
  - deploy

test:
  stage: test
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - make test

release-collector:
  stage: release
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    COLLECTOR_IMAGE: $CI_REGISTRY_IMAGE/collector:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $COLLECTOR_IMAGE -f ./src/collector/Dockerfile ./src
    - docker push $COLLECTOR_IMAGE
  only:
    - master

release-generator:
  stage: release
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    GENERATOR_IMAGE: $CI_REGISTRY_IMAGE/generator:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $GENERATOR_IMAGE -f ./src/generator/Dockerfile ./src
    - docker push $GENERATOR_IMAGE
  only:
    - master

release-dash:
  stage: release
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DASH_IMAGE: $CI_REGISTRY_IMAGE/dash:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DASH_IMAGE -f ./src/dash/Dockerfile ./src
    - docker push $DASH_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  environment:
    name: production
    url: https://thetrains.co.uk/
  script:
    - kubectl apply -f k8s/deployments/
  only:
    - master
