# .gitlab-ci.yml
image: "tiangolo/docker-with-compose"
services:
  - docker:dind   
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  
build:
  stage: build
  script:
    - make up
  
test_environment:
  stage: test
  script:
    - source ./scripts/environment_test.sh
    - docker-compose --version
    - python --version

test_collector:
  stage: test
  script:
    - python collector/collector.py