# .gitlab-ci.yml

image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - docker build -t thetrains-test -f ./tests/Dockerfile .
    - docker run thetrains-test

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Install dependencies
    - apk add --update --no-cache curl git
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-amd64
    - chmod +x skaffold
    # Build images
    - ./skaffold build -f ./k8s/skaffold.yaml
  only:
    - master

deploy:
  stage: deploy
  environment:
    name: production
    url: https://thetrains.co.uk/
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Install dependencies
    - apk add --update --no-cache curl git
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-amd64
    - chmod +x skaffold
    # Build images
    - ./skaffold deploy -f ./k8s/skaffold.yaml
  only:
    - master
