# .gitlab-ci.yml
image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DASH_TEST_IMAGE: $CI_REGISTRY_IMAGE/dash:latest-build
  COLLECTOR_TEST_IMAGE: $CI_REGISTRY_IMAGE/collector:latest-build
  DASH_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/dash:latest
  COLLECTOR_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/collector:latest

stages:
  - build
  - test  
  - release
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-dash:
  stage: build
  script:
    - docker build --pull -t $DASH_TEST_IMAGE dash/
    - docker push $DASH_TEST_IMAGE
  
build-collector:
  stage: build
  script:
    - docker build --pull -t $COLLECTOR_TEST_IMAGE collector/
    - docker push $COLLECTOR_TEST_IMAGE

test_env:
  stage: test
  script:
    - source ./scripts/env_test.sh

release-images:
  stage: release
  script:
    - docker pull $DASH_TEST_IMAGE
    - docker tag $DASH_TEST_IMAGE $DASH_RELEASE_IMAGE
    - docker push $DASH_RELEASE_IMAGE
    - docker pull $COLLECTOR_TEST_IMAGE
    - docker tag $COLLECTOR_TEST_IMAGE $COLLECTOR_RELEASE_IMAGE
    - docker push $COLLECTOR_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<DB-URL>/${DATABASE_URL}/g" ./manifests/dash/config.yaml
    - sed -i "s/<USER>/${NETWORK_RAIL_USER}/g" ./manifests/collector/config.yaml
    - sed -i "s/<PASS>/${NETWORK_RAIL_PASS}/g" ./manifests/collector/config.yaml
    - sed -i "s/<DB-URL>/${DATABASE_URL}/g" ./manifests/collector/config.yaml
    - sed -i "s/<USER>/${POSTGRES_USER}/g" ./manifests/database/config.yaml
    - sed -i "s/<PASS>/${POSTGRES_PASSWORD}/g" ./manifests/database/config.yaml
    - sed -i "s/<DB-NAME>/${POSTGRES_DB}/g" ./manifests/database/config.yaml
    - kubectl apply -f manifests/collector
    - kubectl apply -f manifests/dash