version: '3'

services:

  collector:
    container_name: collector
    restart: "no"
    build: 
      context: ./
      dockerfile: ./collector/Dockerfile
    depends_on:
      - mongo

  dash:
    container_name: dash
    restart: always
    build: 
      context: ./
      dockerfile: ./dash/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo