version: '3'

services:

  collector:
    container_name: collector
    restart: always
    build: 
      context: ./
      dockerfile: ./collector/Dockerfile
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - mongo

  dash:
    container_name: dash
    restart: always
    build: 
      context: ./
      dockerfile: ./dash/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: ./nginx
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: ${NR_USER}
    volumes:
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - dash

volumes:
  letsencrypt: