version: '3'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - thetrains-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: gunicorn -w 1 -b :8000 app:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app

volumes:
  thetrains-db:
