version: '3'

services:

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  collector:
    container_name: collector
    restart: "no"
    build: 
      context: ./
      dockerfile: ./collector/Dockerfile
    depends_on:
      - mongo

  thetrains:
    container_name: thetrains
    restart: "no"
    build: 
      context: ./
      dockerfile: ./thetrains/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo: