version: '3'

services:

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - thetrains_mongo:/data/db
    
volumes:
  thetrains_mongo:
