version: "3"

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - thetrains_mongo:/data/db

  data-collector:
    container_name: data-collector
    restart: "no"
    build:
      context: ./
      dockerfile: ./app/data_collector/Dockerfile
    depends_on:
      - mongo

  graph-generator:
    container_name: graph-generator
    restart: "no"
    build:
      context: ./
      dockerfile: ./app/graph_generator/Dockerfile
    depends_on:
      - mongo

  thetrains-app:
    container_name: thetrains-app
    restart: "no"
    build:
      context: ./
      dockerfile: ./app/thetrains_app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  thetrains_mongo:
