version: "3"

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - main-network

  collector:
    container_name: collector
    restart: "no"
    build:
      context: ./src
      dockerfile: ./collector/Dockerfile
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./src/collector/:/collector/
      - ./src/common/:/collector/common/
    networks:
      - main-network

  generator:
    container_name: generator
    restart: "no"
    build:
      context: ./src
      dockerfile: ./generator/Dockerfile
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./src/generator/:/generator/
      - ./src/common/:/generator/common/
    networks:
      - main-network

  dash:
    container_name: dash
    restart: "no"
    build:
      context: ./src
      dockerfile: ./dash/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./src/dash/:/dash/
      - ./src/common/:/dash/common/
    networks:
      - main-network

volumes:
  mongo-volume:

networks:
  main-network:
