version: '3'

services:

  collector:
    container_name: collector
    restart: "no"
    build: 
      context: ./
      dockerfile: ./collector/Dockerfile
    depends_on:
      - mongo

  thetrains:
    container_name: thetrains
    restart: "no"
    build: 
      context: ./
      dockerfile: ./thetrains/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo