apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: ./
    docker:
      dockerfile: ./thetrains/Dockerfile
    image: registry.gitlab.com/joshtingey/thetrains/thetrains
  - context: ./
    docker:
      dockerfile: ./collector/Dockerfile
    image: registry.gitlab.com/joshtingey/thetrains/collector
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - manifests/thetrains/*
    - manifests/collector/*