apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc
  namespace: thetrains
  labels:
    app: postgres
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 20Gi
  storageClassName: rook-ceph-block