apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: thetrains
  labels:
    app: collector
data:
  NR_USER: <NR_USER>
  NR_PASS: <NR_PASS>
  DB_USER: <DB_USER>
  DB_PASS: <DB_PASS>
  DB_NAME: <DB_NAME>