apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: collector
  namespace: thetrains
spec:
  schedule: "0 */1 * * *" # Run every hour on the hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collector
            image: docker.io/joshtingey/thetrains-collector
            envFrom:
              - configMapRef:
                  name: collector-config
          restartPolicy: OnFailure