apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: thetrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: registry.gitlab.com/joshtingey/thetrains/collector:latest
        envFrom:
          - configMapRef:
              name: collector-config
      restartPolicy: Always