apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/joshtingey/the-trains/collector
      context: ./src
      docker:
        dockerfile: ./collector/Dockerfile
    - image: registry.gitlab.com/joshtingey/the-trains/generator
      context: ./src
      docker:
        dockerfile: ./generator/Dockerfile
    - image: registry.gitlab.com/joshtingey/the-trains/dash
      context: ./src
      docker:
        dockerfile: ./dash/Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/deployments/collector.yaml
      - ./k8s/deployments/generator.yaml
      - ./k8s/deployments/dash.yaml
