apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: ghcr.io/joshtingey/collector
      #context: ./src
      docker:
        dockerfile: ./src/collector/Dockerfile
    - image: ghcr.io/joshtingey/generator
      #context: ./src
      docker:
        dockerfile: ./src/generator/Dockerfile
    - image: ghcr.io/joshtingey/dash
      #context: ./src
      docker:
        dockerfile: ./src/dash/Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/deployments/collector.yaml
      - ./k8s/deployments/generator.yaml
      - ./k8s/deployments/dash.yaml
