apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: thetrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - name: data-collector
          image: registry.gitlab.com/joshtingey/the-trains/data-collector:latest
          imagePullPolicy: "Always"
      restartPolicy: Always
