apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: thetrains
  labels:
    app: mongo
data:
  MONGO_INITDB_ROOT_USERNAME: <MONGO_INITDB_ROOT_USERNAME>
  MONGO_INITDB_ROOT_PASSWORD: <MONGO_INITDB_ROOT_USERNAME>

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: thetrains
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
  selector:
    app: mongo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
  namespace: thetrains
  labels:
    app: mongo
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 20Gi
  storageClassName: microk8s-hostpath

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: thetrains
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        envFrom:
          - configMapRef:
              name: mongo-config
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc