apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/joshtingey/thetrains/thetrains
    context: ./
    docker:
      dockerfile: ./thetrains/Dockerfile
  - image: registry.gitlab.com/joshtingey/thetrains/collector
    context: ./
    docker:
      dockerfile: ./collector/Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - manifests/thetrains/deployment.yaml
    - manifests/collector/deployment.yaml