apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: thetrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: ghcr.io/joshtingey/collector:latest
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: thetrains-config
      imagePullSecrets:
        - name: githubregistrykey
      restartPolicy: Always
