apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash
  namespace: thetrains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: registry.gitlab.com/joshtingey/thetrains/dash:latest
        envFrom:
          - configMapRef:
              name: dash-config
        ports:
        - containerPort: 8000